server:
  port: 8080

#密码见印象笔记
spring:
  datasource:
    url: jdbc:mysql://116.196.91.182:13306/tff?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password:
  jpa:
    show-sql: true
logging:
  group:
    tff: com.tff
  level:
    tff: debug
